spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darik
    username: postgres
    password: 1232002
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        default_schema: sc_network
  security:
    user:
      name: admin
      password: $2a$12$gaOmpwWi/0L6OZnR9wnQlOZVqhwH94xFiQ9t9.4/ya5L1vRPxwEaK
      roles: ADMIN
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: n7meless@yandex.ru
    password: dcwrmywsnpsnghkp



server:
  port: 4000
  error:
    include-message: always

application:
  security:
    access-token-secret: very_long_and_secure_and_safe_access_key
    refresh-token-secret: very_long_and_secure_and_safe_refresh_key
    access-token-validity: 20
    refresh-token-validity: 10080
    allowed-origins: http://localhost:4000, http://localhost:3000, http://localhost:8000
  frontend:
    default-url: http://localhost:8000
